// Generated by FlutterFire CLI — project: smartcheckinap
// Do not edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate native configs.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTd3w7oU0hhm3KNadSqebigfMSrRg305M',
    appId: '1:411190185210:web:640e1f0f42b38b47028d43',
    messagingSenderId: '411190185210',
    projectId: 'smartcheckinap',
    authDomain: 'smartcheckinap.firebaseapp.com',
    storageBucket: 'smartcheckinap.firebasestorage.app',
    measurementId: 'G-L00Z794VXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7X_ubuQ--1oWER9saSKy3bBuIUuwSFfM',
    appId: '1:411190185210:android:e69dc3d96a228aad028d43',
    messagingSenderId: '411190185210',
    projectId: 'smartcheckinap',
    storageBucket: 'smartcheckinap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTd3w7oU0hhm3KNadSqebigfMSrRg305M',
    appId: '1:411190185210:ios:placeholder',
    messagingSenderId: '411190185210',
    projectId: 'smartcheckinap',
    storageBucket: 'smartcheckinap.firebasestorage.app',
    iosBundleId: 'com.example.smartCheckinApp',
  );
}
